name: nni_training_env
channels:
  - conda-forge
  - rapidsai
  - anaconda
dependencies:
  - cudatoolkit=10.2
  - python=3.7
  - rapids
  - pip
  - pip:
    - snakemake
    - numpy
    - deepmerge
    - nni==1.9
    - python-Levenshtein
    - matplotlib
    - scikit-learn
    - seaborn
    - matplotlib
    - gensim
    - pandas
    - scipy
    - xgboost
    - torch
    - fastai
